kind: PersistentVolumeClaim
# NOTE: this PVC will be used by both the GFS writer pod and the frontend nginix pods
# the GFS will use it to write data to the volume and the nginx will allow us to view it through the browser
apiVersion: v1
metadata:
  name: gke-filestore-pvc
  # this name will be used in the  claimName: of the volume: in the write to filestore pod yaml
spec:
  accessModes:
  - ReadWriteMany
  # for Persistent Disk in the older demos this was ReadWriteOnce. Since were are using Google Filestore now
  # we can do a ReadWriteMany (rwx)
  #storageClassName: standard-rwx
  storageClassName: filestore-storage-class
  # this needs to change since in this setup we are using custom storage class
  # the custom storageclassname is in teh filestorageclass yaml "filestore-storage-class"
  resources:
    requests:
      storage: 1Ti
